status_mapping = {
    "PCSC": {"status": "pickup", "sub_status": "pickup scheduled"},
    "PCUP": {"status": "in transit", "sub_status": "picked up"},
    "PCNO": {"status": "pickup", "sub_status": "not picked"},
    "PCAW": {"status": "pickup", "sub_status": "pickup awaited"},
    "PCAN": {"status": "pickup", "sub_status": "archived"},
    "BKD": {"status": "booked", "sub_status": "booked"},
    "IPMF": {"status": "in transit", "sub_status": "in transit"},
    "OPMF": {"status": "in transit", "sub_status": "in transit"},
    "ORMF": {"status": "in transit", "sub_status": "in transit"},
    "IBMD": {"status": "in transit", "sub_status": "in transit"},
    "OBMD": {"status": "in transit", "sub_status": "in transit"},
    "IBMN": {"status": "in transit", "sub_status": "in transit"},
    "OBMN": {"status": "in transit", "sub_status": "in transit"},
    "IMBM": {"status": "in transit", "sub_status": "in transit"},
    "OMBM": {"status": "in transit", "sub_status": "in transit"},
    "IRBO": {"status": "in transit", "sub_status": "in transit"},
    "ORBO": {"status": "in transit", "sub_status": "in transit"},
    "CDIN": {"status": "in transit", "sub_status": "in transit"},
    "CDOUT": {"status": "in transit", "sub_status": "in transit"},
    "ARAP": {"status": "in transit", "sub_status": "arrived at airport"},
    "LNRC": {"status": "pickup", "sub_status": "pickup failed"},
    "CSCL": {"status": "in transit", "sub_status": "in transit"},
    "CHLD": {"status": "in transit", "sub_status": "customs heldup"},
    "HLDUP": {"status": "in transit", "sub_status": "held up"},
    "IRMF": {"status": "in transit", "sub_status": "mis route"},
    "OUTDLV": {"status": "out for delivery", "sub_status": "out for delivery"},
    "NONDLV": {"status": "NDR", "sub_status": "NDR"},
    "DLV": {"status": "delivered", "sub_status": "delivered"},
    "IRTO": {"status": "RTO", "sub_status": "RTO initiated"},
    "RTO": {"status": "RTO", "sub_status": "RTO processed"},
    "RTOOPMF": {"status": "RTO", "sub_status": "RTO in transit"},
    "RTOIPMF": {"status": "RTO", "sub_status": "RTO in transit"},
    "RTOIRMF": {"status": "RTO", "sub_status": "RTO in transit"},
    "RTOOBMD": {"status": "RTO", "sub_status": "RTO in transit"},
    "RTOIBMD": {"status": "RTO", "sub_status": "RTO in transit"},
    "RTOOBMN": {"status": "RTO", "sub_status": "RTO in transit"},
    "RTOIBMN": {"status": "RTO", "sub_status": "RTO in transit"},
    "RTOOMBM": {"status": "RTO", "sub_status": "RTO in transit"},
    "RTOIMBM": {"status": "RTO", "sub_status": "RTO in transit"},
    "RTOORBO": {"status": "RTO", "sub_status": "RTO in transit"},
    "RTOIRBO": {"status": "RTO", "sub_status": "RTO in transit"},
    "RTOCDOUT": {"status": "RTO", "sub_status": "RTO in transit"},
    "RTOCDIN": {"status": "RTO", "sub_status": "RTO in transit"},
    "RTOINSCAN": {"status": "RTO", "sub_status": "RTO in transit"},
    "RTOOUTDLV": {"status": "RTO", "sub_status": "RTO out for delivery"},
    "RETURND": {"status": "RTO", "sub_status": "RTO out for delivery"},
    "RTORETURND": {"status": "RTO", "sub_status": "RTO out for delivery"},
    "RTONONDLV": {"status": "RTO", "sub_status": "RTO not delivered"},
    "RTODLV": {"status": "RTO", "sub_status": "RTO delivered"},
    "SPL": {"status": "booked", "sub_status": "booked"},
    "SETRTO": {"status": "RTO", "sub_status": "RTO initiated"},
    "RTOW": {"status": "RTO", "sub_status": "RTO pending"},
    "STOPDLV": {"status": "NDR", "sub_status": "NDR"},
    "REVOKESTOPDLV": {"status": "in transit", "sub_status": "in transit"},
    "PCRA": {"status": "pickup", "sub_status": "pickup reassigned"},
    "RTOORMF": {"status": "RTO", "sub_status": "RTO mis route"},
    "RTORADCDIN": {"status": "RTO", "sub_status": "RTO in transit"},
    "PREPERD": {"status": "in transit", "sub_status": "in transit"},
    "RTOPREPERD": {"status": "RTO", "sub_status": "RTO in transit"},
    "SUI": {"status": "in transit", "sub_status": "in transit"},
    "DRAW": {"status": "in transit", "sub_status": "in transit"},
    "DRSC": {"status": "in transit", "sub_status": "in transit"},
    "DRCOM": {"status": "in transit", "sub_status": "in transit"},
    "DRCAN": {"status": "in transit", "sub_status": "in transit"},
    "DRREC": {"status": "in transit", "sub_status": "in transit"},
    "INSCAN": {"status": "in transit", "sub_status": "in transit"},
    "RADCDIN": {"status": "in transit", "sub_status": "in transit"},
    "HELDUP": {"status": "in transit", "sub_status": "in transit"},
    "RELHLD": {"status": "in transit", "sub_status": "in transit"},
    "RTOBKD": {"status": "RTO", "sub_status": "RTO initiated"},
    "SVD": {"status": "in transit", "sub_status": "in transit"},
}
