status_mapping = {
    "DRC": {"status": "booked", "sub_status": "booked"},
    "PUC": {"status": "pickup", "sub_status": "pick up pending"},
    "OFP": {"status": "pickup", "sub_status": "out for pickup"},
    "PUD": {"status": "in transit", "sub_status": "picked up"},
    "PND": {"status": "pickup", "sub_status": "picked failed"},
    "PKD": {"status": "in transit", "sub_status": "picked up"},
    "IT": {"status": "in transit", "sub_status": "in transit"},
    "RAD": {"status": "in transit", "sub_status": "in transit"},
    "OFD": {
        "status": "out for delivery",
        "sub_status": "out for delivery",
    },
    "UD": {"status": "NDR", "sub_status": "NDR"},
    "DLVD": {"status": "delivered", "sub_status": "delivered"},
    "LOST": {"status": "NDR", "sub_status": "lost"},
    "RTON": {"status": "RTO", "sub_status": "RTO initiated"},
    "RTO": {"status": "RTO", "sub_status": "RTO initiated"},
    "RTO-IT": {"status": "RTO", "sub_status": "RTO in transit"},
    "RAO": {"status": "RTO", "sub_status": "RTO in transit"},
    "RTO-OFD": {"status": "RTO", "sub_status": "RTO in transit"},
    "RTD": {"status": "RTO", "sub_status": "RTO delivered"},
    "RTU": {"status": "RTO", "sub_status": "RTO in transit"},
    "STD": {"status": "in transit", "sub_status": "in transit"},
    "STG": {"status": "in transit", "sub_status": "in transit"},
    "RTO-STG": {"status": "in transit", "sub_status": "in transit"},
}
