status_mapping = {
    "PU": {
        "016-S": {"status": "pickup", "sub_status": "pickup failed"},
        "017-S": {"status": "pickup", "sub_status": "pickup failed"},
        "018-S": {"status": "pickup", "sub_status": "pickup failed"},
        "019-S": {"status": "pickup", "sub_status": "pickup failed"},
        "500-S": {"status": "pickup", "sub_status": "pickup pending"},
        "500-T": {"status": "pickup", "sub_status": "pickup pending"},
        "501-S": {"status": "pickup", "sub_status": "out for pickup"},
        "501-T": {"status": "pickup", "sub_status": "pickup rescheduled"},
        "502-S": {"status": "pickup", "sub_status": "pickup cancelled"},
        "502-T": {"status": "pickup", "sub_status": "pickup rescheduled"},
        "503-S": {"status": "pickup", "sub_status": "pickup cancelled"},
        "503-T": {"status": "pickup", "sub_status": "pickup rescheduled"},
        "504-S": {"status": "pickup", "sub_status": "pickup pending"},
        "504-T": {"status": "pickup", "sub_status": "pickup cancelled"},
        "505-T": {"status": "pickup", "sub_status": "pickup cancelled"},
        "506-T": {"status": "pickup", "sub_status": "pickup cancelled"},
        "507-T": {"status": "pickup", "sub_status": "pickup cancelled"},
        "508-T": {"status": "pickup", "sub_status": "pickup failed"},
        "509-T": {"status": "pickup", "sub_status": "pickup failed"},
        "510-T": {"status": "pickup", "sub_status": "pickup failed"},
        "511-T": {"status": "pickup", "sub_status": "pickup failed"},
        "512-T": {"status": "pickup", "sub_status": "pickup failed"},
        "513-T": {"status": "pickup", "sub_status": "pickup failed"},
        "514-T": {"status": "pickup", "sub_status": "pickup failed"},
        "531-T": {"status": "pickup", "sub_status": "pickup failed"},
        "532-T": {"status": "pickup", "sub_status": "pickup failed"},
        "533-T": {"status": "pickup", "sub_status": "pickup rescheduled"},
        "534-T": {"status": "pickup", "sub_status": "pickup failed"},
        "535-T": {"status": "pickup", "sub_status": "pickup cancelled"},
        "536-T": {"status": "pickup", "sub_status": "pickup failed"},
        "537-T": {"status": "pickup", "sub_status": "pickup failed"},
        "538-T": {"status": "pickup", "sub_status": "pickup failed"},
        "539-T": {"status": "pickup", "sub_status": "pickup failed"},
        "540-T": {"status": "pickup", "sub_status": "pickup failed"},
        "541-T": {"status": "pickup", "sub_status": "pickup failed"},
        "542-T": {"status": "pickup", "sub_status": "pickup failed"},
        "543-T": {"status": "pickup", "sub_status": "pickup failed"},
        "544-T": {"status": "pickup", "sub_status": "pickup pending"},
        "555-T": {"status": "pickup", "sub_status": "pickup rescheduled"},
        "590-T": {"status": "pickup", "sub_status": "pickup pending"},
        "591-T": {"status": "pickup", "sub_status": "pickup pending"},
        "592-T": {"status": "pickup", "sub_status": "pickup cancelled"},
        "593-T": {"status": "pickup", "sub_status": "pickup pending"},
        "594-T": {"status": "pickup", "sub_status": "pickup pending"},
        "595-T": {"status": "pickup", "sub_status": "pickup pending"},
        "596-T": {"status": "pickup", "sub_status": "pickup cancelled"},
        "505-S": {"status": "pickup", "sub_status": "pickup pending"},
        "506-S": {"status": "pickup", "sub_status": "pickup pending"},
        "561-T": {"status": "pickup", "sub_status": "pickup cancelled"},
        "562-T": {"status": "pickup", "sub_status": "pickup cancelled"},
        "563-T": {"status": "pickup", "sub_status": "pickup cancelled"},
        "564-T": {"status": "pickup", "sub_status": "pickup pending"},
        "565-T": {"status": "pickup", "sub_status": "pickup pending"},
        "030-S": {"status": "pickup", "sub_status": "pickup pending"},
        "031-S": {"status": "pickup", "sub_status": "pickup cancelled"},
        "566-T": {"status": "pickup", "sub_status": "pickup rescheduled"},
    },
    "DL": {
        "000-T": {"status": "delivered", "sub_status": "delivered"},
        "021-T": {"status": "lost", "sub_status": "lost"},
        "025-T": {"status": "destroyed", "sub_status": "destroyed"},
        "099-T": {"status": "lost", "sub_status": "lost"},
        "135-T": {"status": "lost", "sub_status": "lost"},
        "178-T": {"status": "damaged", "sub_status": "damaged"},
        "070-T": {"status": "destroyed", "sub_status": "destroyed"},
        "026-T": {"status": "booked", "sub_status": "booked"},
        "098-T": {"status": "pickup", "sub_status": "pickup cancelled"},
        "000-RT": {"status": "RTO", "sub_status": "RTO delivered"},
        "021-RT": {"status": "lost", "sub_status": "lost"},
        "025-RT": {"status": "destroyed", "sub_status": "destroyed"},
        "099-RT": {"status": "lost", "sub_status": "lost"},
        "135-RT": {"status": "lost", "sub_status": "lost"},
        "178-RT": {"status": "damaged", "sub_status": "damaged"},
        "070-RT": {"status": "destroyed", "sub_status": "destroyed"},
        "026-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "098-RT": {"status": "pickup", "sub_status": "pickup cancelled"},
    },
    "RD": {
        "027-T": {"status": "in transit", "sub_status": "in transit"},
        "050-T": {"status": "in transit", "sub_status": "in transit"},
        "132-T": {"status": "in transit", "sub_status": "in transit"},
        "105-T": {"status": "RTO", "sub_status": "RTO delivered"},
        "027-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "050-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "132-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "105-RT": {"status": "RTO", "sub_status": "RTO delivered"},
    },
    "RD": {
        "016-T": {"status": "RTO", "sub_status": "RTO in transit"},
        "104-T": {"status": "RTO", "sub_status": "RTO initiated"},
        "123-T": {"status": "RTO", "sub_status": "RTO in transit"},
        "188-T": {"status": "RTO", "sub_status": "RTO delivered"},
        "016-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "074-RT": {"status": "RTO", "sub_status": "RTO initiated"},
        "104-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "123-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "188-RT": {"status": "RTO", "sub_status": "RTO delivered"},
    },
    "UD": {
        "024-S": {"status": "NDR", "sub_status": "NDR"},
        "025-S": {"status": "in transit", "sub_status": "in transit"},
        "001-S": {"status": "in transit", "sub_status": "in transit"},
        "001-T": {"status": "NDR", "sub_status": "NDR"},
        "002-S": {"status": "out for delivery", "sub_status": "out for delivery"},
        "002-T": {"status": "NDR", "sub_status": "NDR"},
        "003-S": {"status": "in transit", "sub_status": "in transit"},
        "003-T": {"status": "NDR", "sub_status": "NDR"},
        "004-S": {"status": "in transit", "sub_status": "in transit"},
        "004-T": {"status": "NDR", "sub_status": "NDR"},
        "005-S": {"status": "in transit", "sub_status": "in transit"},
        "005-T": {"status": "NDR", "sub_status": "NDR"},
        "007-S": {"status": "in transit", "sub_status": "in transit"},
        "007-T": {"status": "in transit", "sub_status": "in transit"},
        "008-T": {"status": "NDR", "sub_status": "NDR"},
        "009-S": {"status": "in transit", "sub_status": "in transit"},
        "009-T": {"status": "NDR", "sub_status": "NDR"},
        "010-S": {"status": "in transit", "sub_status": "in transit"},
        "010-T": {"status": "NDR", "sub_status": "NDR"},
        "011-S": {"status": "in transit", "sub_status": "in transit"},
        "011-T": {"status": "NDR", "sub_status": "NDR"},
        "012-S": {"status": "in transit", "sub_status": "in transit"},
        "012-T": {"status": "NDR", "sub_status": "NDR"},
        "013-T": {"status": "NDR", "sub_status": "NDR"},
        "014-T": {"status": "NDR", "sub_status": "NDR"},
        "015-S": {"status": "in transit", "sub_status": "in transit"},
        "015-T": {"status": "NDR", "sub_status": "NDR"},
        "017-T": {"status": "NDR", "sub_status": "NDR"},
        "019-T": {"status": "NDR", "sub_status": "NDR"},
        "020-S": {"status": "in transit", "sub_status": "in transit"},
        "020-T": {"status": "NDR", "sub_status": "NDR"},
        "021-S": {"status": "in transit", "sub_status": "in transit"},
        "022-S": {"status": "in transit", "sub_status": "in transit"},
        "023-S": {"status": "in transit", "sub_status": "in transit"},
        "024-T": {"status": "in transit", "sub_status": "in transit"},
        "029-T": {"status": "NDR", "sub_status": "NDR"},
        "032-T": {"status": "in transit", "sub_status": "in transit"},
        "033-T": {"status": "in transit", "sub_status": "in transit"},
        "034-T": {"status": "NDR", "sub_status": "NDR"},
        "035-T": {"status": "in transit", "sub_status": "in transit"},
        "036-T": {"status": "in transit", "sub_status": "in transit"},
        "037-T": {"status": "in transit", "sub_status": "in transit"},
        "044-T": {"status": "NDR", "sub_status": "NDR"},
        "045-T": {"status": "NDR", "sub_status": "NDR"},
        "046-T": {"status": "NDR", "sub_status": "NDR"},
        "048-T": {"status": "in transit", "sub_status": "in transit"},
        "049-T": {"status": "in transit", "sub_status": "in transit"},
        "052-T": {"status": "in transit", "sub_status": "in transit"},
        "054-T": {"status": "in transit", "sub_status": "in transit"},
        "055-T": {"status": "in transit", "sub_status": "in transit"},
        "057-T": {"status": "in transit", "sub_status": "in transit"},
        "058-T": {"status": "in transit", "sub_status": "in transit"},
        "059-T": {"status": "in transit", "sub_status": "in transit"},
        "060-T": {"status": "RTO", "sub_status": "RTO intiated"},
        "062-T": {"status": "NDR", "sub_status": "NDR"},
        "066-T": {"status": "NDR", "sub_status": "NDR"},
        "067-T": {"status": "NDR", "sub_status": "NDR"},
        "068-T": {"status": "in transit", "sub_status": "in transit"},
        "071-T": {"status": "NDR", "sub_status": "NDR"},
        "073-T": {"status": "in transit", "sub_status": "in transit"},
        "076-T": {"status": "NDR", "sub_status": "NDR"},
        "077-T": {"status": "NDR", "sub_status": "NDR"},
        "078-T": {"status": "NDR", "sub_status": "NDR"},
        "080-T": {"status": "in transit", "sub_status": "in transit"},
        "095-T": {"status": "in transit", "sub_status": "in transit"},
        "096-T": {"status": "in transit", "sub_status": "in transit"},
        "097-T": {"status": "in transit", "sub_status": "in transit"},
        "100-S": {"status": "in transit", "sub_status": "in transit"},
        "100-T": {"status": "in transit", "sub_status": "in transit"},
        "101-T": {"status": "in transit", "sub_status": "in transit"},
        "103-T": {"status": "in transit", "sub_status": "in transit"},
        "106-T": {"status": "in transit", "sub_status": "in transit"},
        "107-T": {"status": "in transit", "sub_status": "in transit"},
        "110-T": {"status": "in transit", "sub_status": "in transit"},
        "111-T": {"status": "in transit", "sub_status": "in transit"},
        "129-T": {"status": "damaged", "sub_status": "damaged"},
        "130-T": {"status": "damaged", "sub_status": "damaged"},
        "133-T": {"status": "in transit", "sub_status": "in transit"},
        "136-T": {"status": "in transit", "sub_status": "in transit"},
        "137-T": {"status": "NDR", "sub_status": "NDR"},
        "139-T": {"status": "NDR", "sub_status": "NDR"},
        "142-T": {"status": "NDR", "sub_status": "NDR"},
        "143-T": {"status": "in transit", "sub_status": "in transit"},
        "145-T": {"status": "in transit", "sub_status": "in transit"},
        "146-T": {"status": "in transit", "sub_status": "in transit"},
        "147-T": {"status": "in transit", "sub_status": "in transit"},
        "148-T": {"status": "NDR", "sub_status": "NDR"},
        "150-T": {"status": "NDR", "sub_status": "NDR"},
        "151-T": {"status": "NDR", "sub_status": "NDR"},
        "152-T": {"status": "in transit", "sub_status": "in transit"},
        "154-T": {"status": "in transit", "sub_status": "in transit"},
        "174-T": {"status": "in transit", "sub_status": "in transit"},
        "175-T": {"status": "NDR", "sub_status": "NDR"},
        "186-T": {"status": "in transit", "sub_status": "in transit"},
        "201-T": {"status": "NDR", "sub_status": "NDR"},
        "202-T": {"status": "NDR", "sub_status": "NDR"},
        "203-T": {"status": "NDR", "sub_status": "NDR"},
        "204-T": {"status": "NDR", "sub_status": "NDR"},
        "205-T": {"status": "NDR", "sub_status": "NDR"},
        "206-T": {"status": "in transit", "sub_status": "in transit"},
        "207-T": {"status": "in transit", "sub_status": "in transit"},
        "208-T": {"status": "in transit", "sub_status": "in transit"},
        "209-T": {"status": "in transit", "sub_status": "in transit"},
        "210-T": {"status": "in transit", "sub_status": "in transit"},
        "211-T": {"status": "in transit", "sub_status": "in transit"},
        "212-T": {"status": "in transit", "sub_status": "in transit"},
        "213-T": {"status": "in transit", "sub_status": "in transit"},
        "214-T": {"status": "in transit", "sub_status": "in transit"},
        "215-T": {"status": "in transit", "sub_status": "in transit"},
        "006-S": {"status": "NDR", "sub_status": "NDR"},
        "014-S": {"status": "in transit", "sub_status": "in transit"},
        "065-T": {"status": "in transit", "sub_status": "in transit"},
        "030-T": {"status": "in transit", "sub_status": "in transit"},
        "301-T": {"status": "in transit", "sub_status": "in transit"},
        "312-T": {"status": "in transit", "sub_status": "in transit"},
        "353-T": {"status": "pickup", "sub_status": "out for pickup"},
        "303-T": {"status": "in transit", "sub_status": "in transit"},
        "308-T": {"status": "NDR", "sub_status": "NDR"},
        "309-T": {"status": "NDR", "sub_status": "NDR"},
        "313-T": {"status": "in transit", "sub_status": "in transit"},
        "305-T": {"status": "in transit", "sub_status": "in transit"},
        "311-T": {"status": "in transit", "sub_status": "in transit"},
        "314-T": {"status": "in transit", "sub_status": "in transit"},
        "306-T": {"status": "in transit", "sub_status": "in transit"},
        "307-T": {"status": "in transit", "sub_status": "in transit"},
        "166-T": {"status": "in transit", "sub_status": "in transit"},
        "027-S": {"status": "in transit", "sub_status": "in transit"},
        "351-T": {"status": "pickup", "sub_status": "pickup pending"},
        "302-T": {"status": "NDR", "sub_status": "NDR"},
        "304-T": {"status": "NDR", "sub_status": "NDR"},
        "310-T": {"status": "NDR", "sub_status": "NDR"},
        "315-T": {"status": "NDR", "sub_status": "NDR"},
        "008-S": {"status": "in transit", "sub_status": "in transit"},
        "026-S": {"status": "in transit", "sub_status": "in transit"},
        "217-T": {"status": "in transit", "sub_status": "in transit"},
        "218-T": {"status": "in transit", "sub_status": "in transit"},
        "187-T": {"status": "NDR", "sub_status": "NDR"},
        "185-T": {"status": "in transit", "sub_status": "in transit"},
        "106-S": {"status": "in transit", "sub_status": "in transit"},
        "140-T": {"status": "in transit", "sub_status": "in transit"},
        "179-T": {"status": "in transit", "sub_status": "in transit"},
        "180-T": {"status": "in transit", "sub_status": "in transit"},
        "181-T": {"status": "in transit", "sub_status": "in transit"},
        "182-T": {"status": "in transit", "sub_status": "in transit"},
        "183-T": {"status": "in transit", "sub_status": "in transit"},
        "777-T": {"status": "NDR", "sub_status": "NDR"},
        "219-T": {"status": "in transit", "sub_status": "in transit"},
        "223-T": {"status": "in transit", "sub_status": "in transit"},
        "189-T": {"status": "NDR", "sub_status": "NDR"},
        "224-T": {"status": "in transit", "sub_status": "in transit"},
        "221-T": {"status": "in transit", "sub_status": "in transit"},
        "222-T": {"status": "in transit", "sub_status": "in transit"},
        "316-T": {"status": "NDR", "sub_status": "NDR"},
        "220-T": {"status": "in transit", "sub_status": "in transit"},
        "352-T": {"status": "pickup", "sub_status": "pickup pending"},
        "121-T": {"status": "NDR", "sub_status": "NDR"},
        "120-T": {"status": "in transit", "sub_status": "in transit"},
        "042-T": {"status": "NDR", "sub_status": "NDR"},
        "056-T": {"status": "NDR", "sub_status": "NDR"},
        "190-T": {"status": "untraceable", "sub_status": "untraceable"},
        "191-T": {"status": "in transit", "sub_status": "in transit"},
        "192-T": {"status": "in transit", "sub_status": "in transit"},
        "028-S": {"status": "in transit", "sub_status": "in transit"},
        "127-S": {"status": "in transit", "sub_status": "in transit"},
        "193-T": {"status": "NDR", "sub_status": "NDR"},
        "029-S": {"status": "NDR", "sub_status": "NDR"},
        "037-S": {"status": "in transit", "sub_status": "in transit"},
        "137-S": {"status": "in transit", "sub_status": "in transit"},
        "124-T": {"status": "in transit", "sub_status": "in transit"},
        "200-T": {"status": "in transit", "sub_status": "in transit"},
        "225-T": {"status": "lost", "sub_status": "lost"},
        "024-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "025-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "001-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "001-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "002-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "002-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "003-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "003-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "004-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "004-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "005-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "005-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "007-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "007-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "008-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "009-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "009-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "010-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "010-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "011-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "011-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "012-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "012-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "013-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "014-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "015-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "015-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "017-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "019-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "020-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "020-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "021-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "022-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "023-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "024-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "029-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "032-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "033-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "034-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "035-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "036-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "037-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "044-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "045-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "046-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "048-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "049-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "052-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "054-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "055-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "057-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "058-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "059-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "060-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "062-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "066-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "067-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "068-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "071-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "073-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "076-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "077-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "078-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "080-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "095-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "096-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "097-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "100-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "100-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "101-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "103-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "106-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "107-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "110-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "111-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "129-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "130-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "133-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "136-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "137-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "139-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "142-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "143-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "145-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "146-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "147-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "148-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "150-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "151-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "152-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "154-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "174-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "175-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "186-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "201-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "202-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "203-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "204-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "205-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "206-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "207-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "208-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "209-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "210-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "211-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "212-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "213-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "214-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "215-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "006-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "014-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "065-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "030-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "301-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "312-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "353-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "303-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "308-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "309-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "313-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "305-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "311-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "314-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "306-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "307-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "166-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "027-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "351-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "302-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "304-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "310-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "315-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "008-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "026-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "217-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "218-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "187-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "185-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "106-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "140-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "179-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "180-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "181-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "182-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "183-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "777-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "219-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "223-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "189-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "224-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "221-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "222-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "316-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "220-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "352-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "121-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "120-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "042-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "056-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "190-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "191-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "192-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "028-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "127-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "193-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "029-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "037-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "137-RS": {"status": "RTO", "sub_status": "RTO in transit"},
        "124-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "200-RT": {"status": "RTO", "sub_status": "RTO in transit"},
        "225-RT": {"status": "RTO", "sub_status": "RTO in transit"},
    },
    "RT": {
        "024-S": {"status": "NDR", "sub_status": "NDR"},
        "074-T": {"status": "RTO", "sub_status": "RTO delivered"},
    },
}
