status_mapping = {
    1: {"status": "new", "sub_status": "processing"},
    25: {"status": "new", "sub_status": "processing"},
    2: {"status": "booked", "sub_status": "shipment booked"},
    3: {"status": "new", "sub_status": "new"},
    9: {"status": "new", "sub_status": "new"},
    8: {"status": "cancelled", "sub_status": "cancelled"},
    24: {"status": "cancelled", "sub_status": "cancelled"},
    21: {"status": "cancelled", "sub_status": "cancelled"},
    4: {"status": "pickup", "sub_status": "pickup pending"},
    23: {"status": "pickup", "sub_status": "pickup failed"},
    5: {"status": "in transit", "sub_status": "picked up"},
    6: {"status": "in transit", "sub_status": "in transit"},
    7: {"status": "out for delivery", "sub_status": "out for delivery"},
    18: {"status": "out for delivery", "sub_status": "out for delivery"},
    10: {"status": "delivered", "sub_status": "delivered"},
    11: {"status": "NDR", "sub_status": "NDR"},
    12: {"status": "RTO", "sub_status": "RTO Pending"},
    13: {"status": "RTO", "sub_status": "RTO delivered"},
    17: {"status": "in transit", "sub_status": "in transit"},
    "RTO_IN_TRANSIT": {"status": "RTO", "sub_status": "RTO in transit"},
    16: {"status": "lost", "sub_status": "lost"},
    None: {"status": "", "sub_status": ""},
    "DAMAGED": {"status": "damaged", "sub_status": "damaged"},
}
