client_data = {
    134: {
        "Customer": "Abc Enterprises",
        "Address": "Thoriyali,Rajkot",
        "GSTIN/UIN": None,
        "PAN No.": "AEFPZ4382P",
        "State Code": 24,
        "State": "Gujarat",
    },
    211: {
        "Customer": "Crazy Deals",
        "Address": "H.no.86 3rd floor bhera enclave national market near by pnb bank",
        "GSTIN/UIN": "07AATFV4238L1ZF",
        "PAN No.": "AATFV4238L",
        "State Code": 7,
        "State": "Delhi",
    },
    234: {
        "Customer": "Topex Express Solutions Limited",
        "Address": "Prop. No 70, Ground Floor, Sai Enclave Vilage Pochanpur Extn, Sector 23, New Delhi, South West Delhi",
        "GSTIN/UIN": "07AAJCT4034B1ZO",
        "PAN No.": "AAJCT4034B",
        "State Code": 7,
        "State": "Delhi",
    },
    68: {
        "Customer": "A.R. Enterprises",
        "Address": "1666, Sector 20, Part 3, Huda Colony, Sirsa, Sirsa, Haryana,125055",
        "GSTIN/UIN": "06DROPR8556J1ZU",
        "PAN No.": "DROPR8556J",
        "State Code": 6,
        "State": "Haryana",
    },
    122: {
        "Customer": "Crunchy Fashion Private Limited",
        "Address": "First Floor,101,Block H, Sector 63, Noida, Gautambuddha Nagar,Uttar Pradesh",
        "GSTIN/UIN": "09AAECC7088F1ZE",
        "PAN No.": "AAECC7088F",
        "State Code": 9,
        "State": "Uttarpradesh",
    },
    89: {
        "Customer": "Amardeep Polymers  Pvt Ltd (Shopunick)",
        "Address": "843/3, B/H Ashi Plastic, Rakanpur, Kalol,Gandhinagar, Gujarat, 382721",
        "GSTIN/UIN": "24AAPCA1704R1ZD",
        "PAN No.": "AAPCA1704R",
        "State Code": 24,
        "State": "Gujarat",
    },
    43: {
        "Customer": "Qadri Watches(Mohd Suhan)",
        "Address": "Mathurpur Cb Ganj Barielly",
        "GSTIN/UIN": None,
        "PAN No.": "NPYPS3652Q",
        "State Code": 9,
        "State": "Uttarpradesh",
    },
    54: {
        "Customer": "Safe And Save",
        "Address": "Plot No 768 769A, F 2, Apex Ii, Ganesh Nagar, Main Niwaru Road, Jaipur",
        "GSTIN/UIN": "08AEPPG8395B1Z6",
        "PAN No.": "AEPPG8395B",
        "State Code": 8,
        "State": "Rajasthan",
    },
    107: {
        "Customer": "Ns Traders",
        "Address": "197,Hari Sadan, Raja Ram Mohan Roy Road,, Charni Road(East),Opposite Jain Temple ,Girgaon,, Mumbai, Maharashtra",
        "GSTIN/UIN": None,
        "PAN No.": "AACPR2165F",
        "State Code": 27,
        "State": "Maharashtra ",
    },
    121: {
        "Customer": "Milecto",
        "Address": "Shop No-106, First Floor, Radhika Optima, Unnamed Road, Surat, Nr.Yamuna Chowk, Surat",
        "GSTIN/UIN": "24BEPPL5143F2ZH",
        "PAN No.": "BEPPL5143F",
        "State Code": 24,
        "State": "Gujarat",
    },
    75: {
        "Customer": "Ddisha Associates",
        "Address": "Shop No- 2, Wz- 42, Old Sahib Pura, Tilak Nagar",
        "GSTIN/UIN": None,
        "PAN No.": "ADQPL7864G",
        "State Code": 7,
        "State": "Delhi",
    },
    109: {
        "Customer": "Sk Hub",
        "Address": "2Nd Floor Bhidbhanjan Society ,B/H, Sardar Patel School, Nonea Varachha, Surat City",
        "GSTIN/UIN": None,
        "PAN No.": "BIZPT5161R",
        "State Code": 24,
        "State": "Gujarat",
    },
    120: {
        "Customer": "Books Center",
        "Address": "Shop No 6 Old Nagardas Rd, Opp. Allahabad Bank, Mogra Village, Patel Wadi, Natwar Nagar, Andheri",
        "GSTIN/UIN": None,
        "PAN No.": "BMBPG2863H",
        "State Code": 27,
        "State": "Maharashtra ",
    },
    92: {
        "Customer": "Beauty Bay",
        "Address": "Near Bihar Public School, Ramdeo Nagar Mahadeva Road, Siwan",
        "GSTIN/UIN": None,
        "PAN No.": "JRLPK6680R",
        "State Code": 10,
        "State": "Bihar",
    },
    116: {
        "Customer": "Kiran Enterprises",
        "Address": "Shop Number 1 Gol Bazar, Dhamtari Main Road, Dhamtari, Chhattisgarh, 493773",
        "GSTIN/UIN": None,
        "PAN No.": "AGTPK3162C",
        "State Code": 22,
        "State": "Chattisgarh",
    },
    26: {
        "Customer": "Sai Ram Enterprises",
        "Address": "Ground Floor, Flat No 229, Gh8, Paschim Vihar, New Delhi,, North West Delhi, Delhi, 110087",
        "GSTIN/UIN": "07GRNPK1511A1Z7",
        "PAN No.": "GRNPK1511A",
        "State Code": 7,
        "State": "Delhi",
    },
    57: {
        "Customer": "Sanjeevani Herbals",
        "Address": "Near Bus Stop Lakhani",
        "GSTIN/UIN": None,
        "PAN No.": "ETJPS2980H",
        "State Code": 27,
        "State": "Maharashtra ",
    },
    125: {
        "Customer": "Skp Enterprises",
        "Address": "House No .608, Bamala Road,New Housing Board, Sirsa,Haryana-125055",
        "GSTIN/UIN": None,
        "PAN No.": "AGEPP4526A",
        "State Code": 6,
        "State": "Haryana",
    },
    101: {
        "Customer": "Fohogo Lifestyle Llp",
        "Address": "House No 42, Block -2, Roop Nagar New Delhi",
        "GSTIN/UIN": "07AAIFF9525B1ZJ",
        "PAN No.": "AAIFF9525B",
        "State Code": 7,
        "State": "Delhi",
    },
    82: {
        "Customer": "3Brocases",
        "Address": "75A, 2Nd Floor, Phase 2 , Badli Industrial Area",
        "GSTIN/UIN": None,
        "PAN No.": "BWYPR3242Q",
        "State Code": 7,
        "State": "Delhi",
    },
    99: {
        "Customer": "Dash Lifestyle",
        "Address": "Tenament No-F-12,Karmacharinagar Co Op, Housing Society Ltd, B/H Karmacharinagar School, Near  Rannapark Ghatlodia",
        "GSTIN/UIN": None,
        "PAN No.": "DLWPR2323K",
        "State Code": 24,
        "State": "Gujarat",
    },
    18: {
        "Customer": "Hedge Enterprises",
        "Address": "Ground Floor, Hedge Enterprises Shop No13, Vrindavan Paradise, Vasant Valley Road, Kalayan, West, Thane , Maharashtra",
        "GSTIN/UIN": "27BRNPP7328D1ZG",
        "PAN No.": "BRNPP7328D",
        "State Code": 27,
        "State": "Maharashtra ",
    },
    22: {
        "Customer": "Root Ow",
        "Address": "Beniwal,1214,Sector-6 Bahadugarh, Jhajjar, Haryana 124507",
        "GSTIN/UIN": None,
        "PAN No.": "AMSPB6072H",
        "State Code": 6,
        "State": "Haryana",
    },
    117: {
        "Customer": "Prosavvy Luxuries Pvt Ltd(Shipnick)",
        "Address": "Ground Floor, A-1/3, Paschim Vihar,, New Delhi, West Delhi, Delhi, 110063",
        "GSTIN/UIN": "07AANCP0432B1ZU",
        "PAN No.": "AANCP0432B",
        "State Code": 7,
        "State": "Delhi",
    },
    132: {
        "Customer": "Aarin Enterprises",
        "Address": "1666, Sector 20, Sirsa, Jan Aushadhi Park, Sirsa",
        "GSTIN/UIN": "06FARPS9502K1ZX",
        "PAN No.": "FARPS9502K",
        "State Code": 6,
        "State": "Haryana",
    },
    9: {
        "Customer": "Laxminaryan  Retail",
        "Address": "Ground Floor.3. Dhanalakshmi Society, Hirawadi Road, Jay Gurudev Mall,Saijpur Bogha, Ahmedabad",
        "GSTIN/UIN": "24BVSPC2341A1Z5",
        "PAN No.": "BVSPC2341A",
        "State Code": 24,
        "State": "Gujarat",
    },
    50: {
        "Customer": "Unlimited Greens",
        "Address": "Kh. No-1183,, Ground Floor,, Green Way Nursery, Fatehpur Beri,, Asthal Mandir,, South Delhi",
        "GSTIN/UIN": "07ABUPO8447N1ZJ",
        "PAN No.": "ABUPO8447N",
        "State Code": 7,
        "State": "Delhi",
    },
    108: {
        "Customer": "Balaji Traders",
        "Address": "Prop. No 70, Ground Floor, Sai Enclave Vilage Pochanpur Extn, Sector 23, New Delhi, South West Delhi",
        "GSTIN/UIN": "07AAJCT4034B1ZO",
        "PAN No.": "AAJCT4034B",
        "State Code": 7,
        "State": "Delhi",
    },
    6: {
        "Customer": "All Well Opticals",
        "Address": "277, Bb Ganguly Street, 2Nd Floor, Kolkata",
        "GSTIN/UIN": None,
        "PAN No.": "ANBPM8715E",
        "State Code": 19,
        "State": "Kolkata",
    },
    31: {
        "Customer": "Rk International",
        "Address": "69 A Block, Krishna Enclave, Jharoda Kala",
        "GSTIN/UIN": None,
        "PAN No.": None,
        "State Code": 7,
        "State": "Delhi",
    },
    66: {
        "Customer": "Rajpurohit Movers",
        "Address": "-, Near Bus Stand, Jodhpur Road Bilara, Jodhpur",
        "GSTIN/UIN": "08JNPPK9010M1Z9",
        "PAN No.": "JNPPK9010M",
        "State Code": 8,
        "State": "Rajasthan",
    },
    103: {
        "Customer": "Dk Retail",
        "Address": "264 , 2Nd Floor Fortune The Shopping Island, Near Galaxy Circle Pal, Adajan",
        "GSTIN/UIN": None,
        "PAN No.": "JBZPK5555H",
        "State Code": 24,
        "State": "Gujarat",
    },
    105: {
        "Customer": "Cartngo",
        "Address": "Plot No-58-A G/F, Kh No-643Block-Z, Phase-1, Shyam Vihar, Najafgarh Road, Najafgarh, Po: Najafgarh, Dist: South West Delhi,",
        "GSTIN/UIN": None,
        "PAN No.": "FEOPB5267M",
        "State Code": 7,
        "State": "Delhi",
    },
    None: {
        "Customer": "Nitish Enterprises",
        "Address": "Property No-1364803, Ground Floor, Shiv Nonedan Prasad, Po-Ps-Ram Krishna Nagar, Kankarbagh, Patna, Shaheed Rudal Indane Gas Agency Office, Patna",
        "GSTIN/UIN": "10HMTPK8584D1ZM",
        "PAN No.": "HMTPK8584D",
        "State Code": 10,
        "State": "Bihar",
    },
    98: {
        "Customer": "Golden Times",
        "Address": "Shop No-Lg-2 Nirmala Appartment, Opp Khambhati Wadi , Rustampura Main Road Surat",
        "GSTIN/UIN": None,
        "PAN No.": "CBGPB6738M",
        "State Code": 24,
        "State": "Gujarat",
    },
    16: {
        "Customer": "Label By Ashok",
        "Address": "H No-3062 Dec-62-Gali No-8 Near Achleshwar Mandir, Jawahar Colony-Faridabad",
        "GSTIN/UIN": None,
        "PAN No.": "JETPS4787E",
        "State Code": 6,
        "State": "Haryana",
    },
    76: {
        "Customer": "Narkoda Sarees",
        "Address": "1077, Avdh Market, Ring Road, Surat",
        "GSTIN/UIN": None,
        "PAN No.": None,
        "State Code": 24,
        "State": "Gujarat",
    },
    113: {
        "Customer": "J B International",
        "Address": "Mota Varachha, 1St Floor, B-101, Sai Darshan Sankul,, Near Ram Chowk,Mota Varachaa, Surat",
        "GSTIN/UIN": "24AQJPN3644A1Z6",
        "PAN No.": "AQJPN3644A",
        "State Code": 24,
        "State": "Gujarat",
    },
    24: {
        "Customer": "Nut Roaster",
        "Address": "1214, Sector-6 Bahadurgarh, Jhajjar, Haryana,",
        "GSTIN/UIN": None,
        "PAN No.": "AMSPB6072H",
        "State Code": 6,
        "State": "Haryana",
    },
    137: {
        "Customer": "Sogo Teleshoping",
        "Address": "I-314,, 2Nd Floor,, Karampura Shoping Complex, Karampura, West Delhi",
        "GSTIN/UIN": "07ADSPC0700E1Z4",
        "PAN No.": "ADSPC0700E",
        "State Code": 7,
        "State": "Delhi",
    },
    11: {
        "Customer": "Vijay Popli (Niva)",
        "Address": "498/5 Rishi Kamla Ashirwaad Readymade Market Mehrauli",
        "GSTIN/UIN": None,
        "PAN No.": "AAIPP3775B",
        "State Code": 7,
        "State": "Delhi",
    },
    97: {
        "Customer": "Sm Fragrances",
        "Address": "Nr.Yamuna Chowk, First Floor, Shop No-106, Radhika Optima, Unnamed Road, Mota Varachha, Surat,",
        "GSTIN/UIN": "24BEPPL5143F2ZH",
        "PAN No.": "BEPPL5143F",
        "State Code": 24,
        "State": "Gujarat",
    },
    93: {
        "Customer": "Godash Solutions Private Limited",
        "Address": "Prestige Skytech,, 16Th Floor,, FiNonecial District, Hyderabad, FiNonecial District, Rangareddy",
        "GSTIN/UIN": "36AAFCF6863J1Z7",
        "PAN No.": "AAFCF6863J",
        "State Code": 36,
        "State": "Telangana",
    },
    73: {
        "Customer": "Balaji  Enterprises",
        "Address": "2/2390, Koliwad, Rudarpura, Surat, Surat, Gujarat",
        "GSTIN/UIN": "24ARDPP3756E4ZS",
        "PAN No.": "ARDPP3756E",
        "State Code": 24,
        "State": "Gujarat",
    },
    118: {
        "Customer": "Apna Ship",
        "Address": "Gram Chandisthan Post Besudewpur Thana Kotwali, Basdeopur Munger",
        "GSTIN/UIN": None,
        "PAN No.": "LUXPK9675D",
        "State Code": 10,
        "State": "Bihar",
    },
    64: {
        "Customer": "Aayushman Homeopathy",
        "Address": "Near By Jaat Dharmsala Urban State House No.-462",
        "GSTIN/UIN": None,
        "PAN No.": None,
        "State Code": 6,
        "State": "Haryana",
    },
    110: {
        "Customer": "S K Enterprise",
        "Address": "Gfl Parking Shop, Gfl, Good Luck Textile Market, Ring Road, Surat, Good Luck Textile Market, Surat",
        "GSTIN/UIN": "24GDFPK3294C1ZO",
        "PAN No.": "GDFPK3294C",
        "State Code": 24,
        "State": "Gujarat",
    },
    27: {
        "Customer": "Guru Kripa Plastic",
        "Address": "A52 Old Sindhi Colony, Berasia Road, Huxur Bhopal, Madhya Pradesh-462001",
        "GSTIN/UIN": None,
        "PAN No.": "AKBPT5984F",
        "State Code": 23,
        "State": "Madhya Pradesh ",
    },
    63: {
        "Customer": "S J Marketing",
        "Address": "Ward No 9, Main Road, Shahpura, Bhitoni, Jabalpur, Jabalpur",
        "GSTIN/UIN": "23AWPPJ6223M2Z7",
        "PAN No.": "AWPPJ6223M",
        "State Code": 23,
        "State": "Madhya Pradesh ",
    },
    19: {
        "Customer": "Cross Border Supps Pvt. Ltd_x000D_\n",
        "Address": "38/134,Thoomkuzhy House, Westhill, Calicut,, Athanikkal, Kozhikode, Kerala",
        "GSTIN/UIN": "32AAKCC3941M1ZI",
        "PAN No.": "AAKCC3941M",
        "State Code": 32,
        "State": "Kerala ",
    },
    139: {
        "Customer": "Infinity Shopee",
        "Address": "Bairagiwala,Jassowala, Dehradun, Uttarakhand",
        "GSTIN/UIN": None,
        "PAN No.": "FXXPM7836Q",
        "State Code": 5,
        "State": "Uttarakhand",
    },
    133: {
        "Customer": "21St Century",
        "Address": "Flat No C-3, Third Floor, Plot No 25, Shyam Vihar Phase-2, New Delhi, South West Delhi",
        "GSTIN/UIN": "07AADFZ6388H1ZL",
        "PAN No.": "AADFZ6388H",
        "State Code": 7,
        "State": "Delhi",
    },
    114: {
        "Customer": "Vedanta Holidays",
        "Address": "706, Sargodha Appartments Plot No 13 Sector 7, Dwarka",
        "GSTIN/UIN": None,
        "PAN No.": "AEDPP2098A",
        "State Code": 7,
        "State": "Delhi",
    },
    127: {
        "Customer": "Rita Enterprises",
        "Address": "Green Garden Appartment Flat No I-4 A Hesag,Hatiya,, Ranchi",
        "GSTIN/UIN": None,
        "PAN No.": "DORPR5068P",
        "State Code": 20,
        "State": "Jharkhand",
    },
    186: {
        "Customer": "Fashion Sports",
        "Address": "C 6, TEXTILE COLONY, INDUSTRIAL AREA A, Ludhiana, Punjab",
        "GSTIN/UIN": "03AABFF3773C3ZW",
        "PAN No.": "AABFF3773C",
        "State Code": 3,
        "State": "Punjab",
    },
    138: {
        "Customer": "Smart Joy",
        "Address": "202, Raj Enterprise, Chankya building, 34 street Number, New Jagnath Plot, Near Astron Chowk, Rajkot",
        "GSTIN/UIN": "24GCWPM6024A1ZL",
        "PAN No.": "GCWPM6024A",
        "State Code": 24,
        "State": "Gujarat",
    },
}
