status_mapping = {
    "pickup_awaited": {"status": "pickup", "sub_status": "pickup pending"},
    "pickup_scheduled": {"status": "pickup", "sub_status": "pickup pending"},
    "out_for_pickup": {"status": "pickup", "sub_status": "out for pickup"},
    "in_transit": {"status": "in transit", "sub_status": "in transit"},
    "cancelled": {"status": "cancelled", "sub_status": "cancelled"},
    "out_for_delivery": {
        "status": "out for delivery",
        "sub_status": "out for delivery",
    },
    "delivered": {"status": "delivered", "sub_status": "delivered"},
    "undelivered": {"status": "NDR", "sub_status": "NDR"},
    "rto_initiated": {"status": "RTO", "sub_status": "RTO initiated"},
    "rto": {"status": "RTO", "sub_status": "RTO"},
    "rto_delivered": {"status": "RTO", "sub_status": "RTO delivered"},
    "rto_in_transit": {"status": "RTO", "sub_status": "RTO in transit"},
    "rto_ndr": {"status": "RTO", "sub_status": "NDR"},
    "return_to_sender": {"status": "NDR", "sub_status": "NDR"},
    "lost": {"status": "lost", "sub_status": "lost"},
    "rto_lost": {"status": "RTO", "sub_status": "RTO lost"},
    "rto_damaged": {"status": "RTO", "sub_status": "RTO damaged"},
    "damaged": {"status": "damaged", "sub_status": "damaged"},
    "exception": {"status": "NDR", "sub_status": "NDR"},
}
