status_mapping = {
    3: {"status": "booked", "sub_status": "booked"},
    6: {"status": "in transit", "sub_status": "in transit"},
    7: {"status": "delivered", "sub_status": "delivered"},
    8: {"status": "cancelled", "sub_status": "cancelled"},
    9: {"status": "RTO", "sub_status": "RTO initiated"},
    10: {"status": "RTO", "sub_status": "RTO delivered"},
    12: {"status": "lost", "sub_status": "lost"},
    13: {"status": "pickup", "sub_status": "picked failed"},
    14: {"status": "RTO", "sub_status": "RTO initiated"},
    15: {"status": "pickup", "sub_status": "picked rescheduled"},
    16: {"status": "cancelled", "sub_status": "cancellation requested"},
    17: {
        "status": "out for delivery",
        "sub_status": "out for delivery",
    },
    18: {"status": "in transit", "sub_status": "in transit"},
    19: {"status": "pickup", "sub_status": "out for pickup"},
    20: {"status": "pickup", "sub_status": "picked failed"},
    21: {"status": "NDR", "sub_status": "NDR"},
    22: {"status": "in transit", "sub_status": "in transit"},
    23: {"status": "delivered", "sub_status": "partial delivered"},
    24: {"status": "NDR", "sub_status": "destroyed"},
    25: {"status": "NDR", "sub_status": "damaged"},
    26: {"status": "delivered", "sub_status": "delivered"},
    27: {"status": "pickup", "sub_status": "picked pending"},
    38: {"status": "in transit", "sub_status": "in transit"},
    39: {"status": "in transit", "sub_status": "in transit"},
    40: {"status": "RTO", "sub_status": "NDR"},
    41: {"status": "RTO", "sub_status": "RTO out for delivery"},
    42: {"status": "in transit", "sub_status": "in transit"},
    43: {"status": "delivered", "sub_status": "delivered"},
    44: {"status": "NDR", "sub_status": "disposed"},
    45: {"status": "cancelled", "sub_status": "cancelled"},
    46: {"status": "RTO", "sub_status": "RTO in transit"},
    47: {"status": "RTO", "sub_status": "QC Failed"},
    48: {"status": "in transit", "sub_status": "in transit"},
    49: {"status": "in transit", "sub_status": "in transit"},
    50: {"status": "in transit", "sub_status": "in transit"},
    51: {"status": "in transit", "sub_status": "in transit"},
    52: {"status": "booked", "sub_status": "shipment booked"},
    54: {"status": "in transit", "sub_status": "in transit"},
    55: {"status": "in transit", "sub_status": "in transit"},
    56: {"status": "in transit", "sub_status": "in transit"},
    57: {"status": "in transit", "sub_status": "in transit"},
    59: {"status": "in transit", "sub_status": "in transit"},
    68: {"status": "in transit", "sub_status": "in transit"},
    60: {"status": "in transit", "sub_status": "in transit"},
    61: {"status": "in transit", "sub_status": "in transit"},
    62: {"status": "in transit", "sub_status": "in transit"},
    63: {"status": "in transit", "sub_status": "in transit"},
    67: {"status": "in transit", "sub_status": "in transit"},
    71: {"status": "in transit", "sub_status": "in transit"},
    72: {"status": "in transit", "sub_status": "in transit"},
    75: {"status": "RTO", "sub_status": "RTO lock"},
    76: {"status": "in transit", "sub_status": "untraceable"},
    77: {"status": "NDR", "sub_status": "NDR"},
    78: {"status": "RTO", "sub_status": "RTO in transit"},
}
