status_mapping = {
    "New": {"status": "new", "sub_status": "new"},
    "shipment_created": {"status": "booked", "sub_status": "booked"},
    "pickup_scheduled": {"status": "pickup", "sub_status": "pickup pending"},
    "pickup_out_for_pickup": {"status": "pickup", "sub_status": "out for pickup"},
    "out_for_pickup": {"status": "pickup", "sub_status": "out for pickup"},
    "pickup_reattempt": {"status": "pickup", "sub_status": "pickup rescheduled"},
    "pickup_cancelled": {"status": "pickup", "sub_status": "pickup cancelled"},
    "pickup_complete": {"status": "in transit", "sub_status": "pickup completed"},
    "shipment_pickup_complete": {
        "status": "in transit",
        "sub_status": "pickup completed",
    },
    "shipment_expected": {"status": "in transit", "sub_status": "in transit"},
    "shipment_shipped": {"status": "in transit", "sub_status": "in transit"},
    "lpd_generated": {"status": "in transit", "sub_status": "in transit"},
    "expected": {"status": "in transit", "sub_status": "in transit"},
    "in_transit": {"status": "in transit", "sub_status": "in transit"},
    "shipment_received": {"status": "in transit", "sub_status": "in transit"},
    "received": {"status": "in transit", "sub_status": "in transit"},
    "received_at_dh": {"status": "in transit", "sub_status": "in transit"},
    "out_for_delivery": {
        "status": "out for delivery",
        "sub_status": "out for delivery",
    },
    "shipment_out_for_delivery": {
        "status": "out for delivery",
        "sub_status": "out for delivery",
    },
    "out_for_delivery_update": {
        "status": "out for delivery",
        "sub_status": "out for delivery",
    },
    "delivered": {"status": "delivered", "sub_status": "delivered"},
    "shipment_delivered": {"status": "delivered", "sub_status": "delivered"},
    "delivery_attempt_metadata": {
        "status": "out for delivery",
        "sub_status": "out for delivery",
    },
    "undelivered": {"status": "NDR", "sub_status": "NDR"},
    "shipment_undelivered_attempted": {"status": "NDR", "sub_status": "NDR"},
    "shipment_undelivered_unattempted": {"status": "NDR", "sub_status": "NDR"},
    "unsuccessful_delivery_attempt_due_to_address_issues": {
        "status": "NDR",
        "sub_status": "address not found",
    },
    "undelivered_due_to_rejection_by_customer": {
        "status": "NDR",
        "sub_status": "customer rejected",
    },
    "undelivered_due_to_customer_unavailability": {
        "status": "NDR",
        "sub_status": "customer unavailable",
    },
    "undelivered_due_to_request_for_reschedule": {
        "status": "NDR",
        "sub_status": "customer rescehduled",
    },
    "undelivered_due_to_cash_unavailability": {
        "status": "NDR",
        "sub_status": "COD not ready",
    },
    "unsuccessful_delivery_attempt_due_to_serviceability_issues": {
        "status": "NDR",
        "sub_status": "non serviceable",
    },
    "rto_created": {"status": "RTO", "sub_status": "RTO initiated"},
    "shipment_rto_created": {"status": "RTO", "sub_status": "RTO initiated"},
    "shipment_rto_confirmed": {"status": "RTO", "sub_status": "RTO initiated"},
    "rto_completed": {"status": "RTO", "sub_status": "RTO delivered"},
    "shipment_rto_completed": {"status": "RTO", "sub_status": "RTO delivered"},
    "rto_received": {"status": "RTO", "sub_status": "RTO in transit"},
    "rto_in_transit": {"status": "RTO", "sub_status": "RTO in transit"},
    "rto_in_confirmed": {"status": "RTO", "sub_status": "RTO pending"},
    "shipment_rto_in_transit": {"status": "RTO", "sub_status": "RTO in transit"},
    "rto_dispatched_to_seller": {"status": "RTO", "sub_status": "RTO out for delivery"},
    "rto_cancelled": {"status": "RTO", "sub_status": "RTO cancelled"},
    "lost": {"status": "NDR", "sub_status": "lost"},
    "shipment_lost": {"status": "NDR", "sub_status": "lost"},
    "damaged": {"status": "NDR", "sub_status": "damaged"},
    "untraceable": {"status": "NDR", "sub_status": "untraceable"},
    "return_received": {"status": "RTO", "sub_status": "RTO in transit"},
    "return_expected": {"status": "RTO", "sub_status": "RTO in transit"},
    "return_received_at_dh": {"status": "RTO", "sub_status": "RTO in transit"},
    "return_out_for_delivery": {"status": "RTO", "sub_status": "RTO in transit"},
    "return_undelivered_attempted": {"status": "RTO", "sub_status": "RTO in transit"},
    "return_undelivered_unattempted": {"status": "RTO", "sub_status": "RTO in transit"},
    "return_rejected_by_seller": {"status": "RTO", "sub_status": "RTO in transit"},
    "return_delivered": {"status": "RTO", "sub_status": "RTO delivered"},
    "return_lost": {"status": "lost", "sub_status": "lost"},
    "shipment_rto_cancelled": {"status": "NDR", "sub_status": "NDR"},
    "shipment_update_accepted": {"status": "NDR", "sub_status": "NDR"},
    "shipment_update_failed": {"status": "NDR", "sub_status": "NDR"},
    "shipment_updated": {"status": "NDR", "sub_status": "NDR"},
    "shipment_misrouted": {"status": "in transit", "sub_status": "in transit"},
}
