status_mapping = {
    "101": {"status": "booked", "sub_status": "booked"},
    "106": {"status": "pickup", "sub_status": "pickup canclled"},
    "107": {"status": "pickup", "sub_status": "pickup canclled"},
    "102": {"status": "pickup", "sub_status": "pickup initiated"},
    "103": {"status": "pickup", "sub_status": "out for pickup"},
    "104": {"status": "pickup", "sub_status": "pickup failed"},
    "105": {"status": "pickup", "sub_status": "pickup rescheduled"},
    "119": {"status": "pickup", "sub_status": "pickup scheduled"},
    "118": {"status": "pickup", "sub_status": "pickup rescheduled"},
    "115": {"status": "NDR", "sub_status": "lost"},
    "116": {"status": "NDR", "sub_status": "damaged"},
    "117": {"status": "NDR", "sub_status": "destroyed"},
    "108": {"status": "NDR", "sub_status": "NDR"},
    "109": {"status": "in transit", "sub_status": "in transit"},
    "110": {"status": "in transit", "sub_status": "in transit"},
    "122": {"status": "in transit", "sub_status": "in transit"},
    "123": {"status": "in transit", "sub_status": "in transit"},
    "124": {"status": "in transit", "sub_status": "in transit"},
    "125": {"status": "in transit", "sub_status": "in transit"},
    "126": {"status": "in transit", "sub_status": "in transit"},
    "133": {"status": "in transit", "sub_status": "in transit"},
    "120": {"status": "in transit", "sub_status": "in transit"},
    "121": {
        "status": "out for delivery",
        "sub_status": "out for delivery",
    },
    "112": {"status": "NDR", "sub_status": "NDR"},
    "113": {"status": "delivered", "sub_status": "delivered"},
    "114": {"status": "RTO", "sub_status": "RTO delivered"},
    "138": {"status": "in transit", "sub_status": "in transit"},
    "135": {"status": "in transit", "sub_status": "in transit"},
    "137": {"status": "in transit", "sub_status": "in transit"},
    "136": {"status": "in transit", "sub_status": "in transit"},
    "139": {"status": "in transit", "sub_status": "in transit"},
    "129": {"status": "NDR", "sub_status": "NDR"},
    "130": {"status": "NDR", "sub_status": "NDR"},
    "131": {"status": "NDR", "sub_status": "NDR"},
    "132": {"status": "NDR", "sub_status": "NDR"},
    "127": {"status": "NDR", "sub_status": "NDR"},
    "128": {"status": "NDR", "sub_status": "NDR"},
    "211": {"status": "RTO", "sub_status": "RTO"},
    "222": {"status": "NDR", "sub_status": "NDR"},
    "224": {"status": "NDR", "sub_status": "NDR"},
    "229": {"status": "in transit", "sub_status": "in transit"},
    "230": {"status": "in transit", "sub_status": "in transit"},
    "235": {"status": "in transit", "sub_status": "in transit"},
    "236": {"status": "NDR", "sub_status": "NDR"},
    "241": {"status": "NDR", "sub_status": "NDR"},
    "302": {"status": "NDR", "sub_status": "NDR"},
    "304": {"status": "in transit", "sub_status": "in transit"},
    "310": {"status": "pickup", "sub_status": "pickup rescheduled"},
    "312": {"status": "NDR", "sub_status": "NDR"},
    "313": {"status": "NDR", "sub_status": "NDR"},
    "314": {"status": "NDR", "sub_status": "NDR"},
    "315": {"status": "NDR", "sub_status": "NDR"},
    "316": {"status": "NDR", "sub_status": "NDR"},
    "326": {"status": "NDR", "sub_status": "NDR"},
    "331": {"status": "NDR", "sub_status": "NDR"},
    "332": {"status": "NDR", "sub_status": "NDR"},
    "333": {"status": "NDR", "sub_status": "lost"},
    "402": {"status": "pickup", "sub_status": "pickup rescheduled"},
    "403": {"status": "pickup", "sub_status": "pickup failed"},
    "404": {"status": "pickup", "sub_status": "pickup failed"},
    "405": {"status": "pickup", "sub_status": "pickup failed"},
    "406": {"status": "pickup", "sub_status": "pickup failed"},
    "407": {"status": "pickup", "sub_status": "pickup failed"},
    "408": {"status": "pickup", "sub_status": "pickup failed"},
    "409": {"status": "pickup", "sub_status": "pickup failed"},
    "411": {"status": "pickup", "sub_status": "pickup failed"},
    "413": {"status": "pickup", "sub_status": "pickup failed"},
    "414": {"status": "NDR", "sub_status": "NDR"},
    "415": {"status": "NDR", "sub_status": "NDR"},
    "416": {"status": "pickup", "sub_status": "pickup failed"},
    "417": {"status": "NDR", "sub_status": "NDR"},
    "418": {"status": "NDR", "sub_status": "NDR"},
    "419": {"status": "NDR", "sub_status": "NDR"},
    "420": {"status": "pickup", "sub_status": "pickup failed"},
    "422": {"status": "NDR", "sub_status": "NDR"},
    "425": {"status": "NDR", "sub_status": "NDR"},
    "426": "Reverse pickup failed because of qc checks failed",
    "427": "Pickup cancelled due to larger product size",
    "430": {"status": "NDR", "sub_status": "NDR"},
    "504": "Type_change_from_cod_to_ppd",
    "505": "Cod_value_updated",
    "506": "Declared_value_updated",
    "507": "Consignee_mobile_updated",
    "509": "Consignee_address_updated",
    "600": "RTS_reversal",
    "702": "Seller_refusal_no_claim",
    "777": {"status": "RTO", "sub_status": "RTO delivered"},
    "840": {"status": "NDR", "sub_status": "NDR"},
    "841": {"status": "in transit", "sub_status": "in transit"},
    "842": {"status": "in transit", "sub_status": "in transit"},
    "1225": {"status": "NDR", "sub_status": "NDR"},
    "12241": {"status": "NDR", "sub_status": "NDR"},
    "12242": {"status": "NDR", "sub_status": "NDR"},
    "12243": {"status": "NDR", "sub_status": "NDR"},
    "12244": {"status": "NDR", "sub_status": "NDR"},
    "12245": {"status": "NDR", "sub_status": "NDR"},
    "12246": {"status": "NDR", "sub_status": "NDR"},
    "12247": {"status": "NDR", "sub_status": "NDR"},
    "20001": {"status": "NDR", "sub_status": "NDR"},
    "20002": {"status": "NDR", "sub_status": "NDR"},
    "20003": {"status": "NDR", "sub_status": "NDR"},
    "20701": {"status": "in transit", "sub_status": "in transit"},
    "21001": {"status": "NDR", "sub_status": "NDR"},
    "21002": {"status": "NDR", "sub_status": "NDR"},
    "21003": {"status": "NDR", "sub_status": "NDR"},
    "21004": {"status": "NDR", "sub_status": "NDR"},
    "21501": {"status": "NDR", "sub_status": "NDR"},
    "21502": {"status": "NDR", "sub_status": "NDR"},
    "21601": {"status": "in transit", "sub_status": "in transit"},
    "21602": {"status": "NDR", "sub_status": "NDR"},
    "21603": {"status": "in transit", "sub_status": "in transit"},
    "21701": {"status": "NDR", "sub_status": "NDR"},
    "22101": {"status": "NDR", "sub_status": "NDR"},
    "22102": {"status": "NDR", "sub_status": "NDR"},
    "22103": {"status": "NDR", "sub_status": "NDR"},
    "22104": {"status": "NDR", "sub_status": "NDR"},
    "22105": {"status": "NDR", "sub_status": "NDR"},
    "22106": {"status": "NDR", "sub_status": "NDR"},
    "22107": {"status": "NDR", "sub_status": "NDR"},
    "22108": {"status": "NDR", "sub_status": "NDR"},
    "22109": {"status": "NDR", "sub_status": "NDR"},
    "22111": {"status": "NDR", "sub_status": "NDR"},
    "22301": {"status": "NDR", "sub_status": "NDR"},
    "22303": {"status": "NDR", "sub_status": "NDR"},
    "22701": {"status": "NDR", "sub_status": "NDR"},
    "22704": {"status": "NDR", "sub_status": "NDR"},
    "22705": {"status": "NDR", "sub_status": "NDR"},
    "22801": {"status": "NDR", "sub_status": "NDR"},
    "22901": {"status": "NDR", "sub_status": "NDR"},
    "22903": {"status": "NDR", "sub_status": "NDR"},
    "23101": {"status": "NDR", "sub_status": "NDR"},
    "23102": {"status": "NDR", "sub_status": "NDR"},
    "23201": {"status": "NDR", "sub_status": "NDR"},
    "23202": {"status": "NDR", "sub_status": "NDR"},
    "23701": {"status": "NDR", "sub_status": "NDR"},
    "23801": {"status": "NDR", "sub_status": "NDR"},
    "24001": {"status": "NDR", "sub_status": "NDR"},
    "24002": {"status": "NDR", "sub_status": "NDR"},
    "24003": {"status": "NDR", "sub_status": "NDR"},
    "24202": {"status": "NDR", "sub_status": "NDR"},
    "24204": {"status": "NDR", "sub_status": "NDR"},
    "24455": {"status": "NDR", "sub_status": "NDR"},
    "30101": {"status": "NDR", "sub_status": "damaged"},
    "30201": {"status": "NDR", "sub_status": "NDR"},
    "30202": {"status": "NDR", "sub_status": "damaged"},
    "30203": {"status": "NDR", "sub_status": "damaged"},
    "30204": {"status": "NDR", "sub_status": "damaged"},
    "30401": {"status": "in transit", "sub_status": "in transit"},
    "30402": {"status": "in transit", "sub_status": "in transit"},
    "30403": {"status": "in transit", "sub_status": "in transit"},
    "30404": {"status": "in transit", "sub_status": "in transit"},
    "30405": {"status": "in transit", "sub_status": "in transit"},
    "30406": {"status": "in transit", "sub_status": "in transit"},
    "30407": {"status": "in transit", "sub_status": "in transit"},
    "30408": {"status": "in transit", "sub_status": "in transit"},
    "30409": {"status": "in transit", "sub_status": "in transit"},
    "30410": {"status": "in transit", "sub_status": "in transit"},
    "30411": {"status": "in transit", "sub_status": "in transit"},
    "30412": {"status": "in transit", "sub_status": "in transit"},
    "30413": {"status": "in transit", "sub_status": "in transit"},
    "30414": {"status": "in transit", "sub_status": "in transit"},
    "30415": {"status": "in transit", "sub_status": "in transit"},
    "30501": {"status": "in transit", "sub_status": "in transit"},
    "30502": {"status": "in transit", "sub_status": "in transit"},
    "30503": {"status": "in transit", "sub_status": "in transit"},
    "30504": {"status": "in transit", "sub_status": "in transit"},
    "30505": {"status": "in transit", "sub_status": "in transit"},
    "30506": {"status": "in transit", "sub_status": "in transit"},
    "30507": {"status": "in transit", "sub_status": "in transit"},
    "30508": {"status": "in transit", "sub_status": "in transit"},
    "30509": {"status": "in transit", "sub_status": "in transit"},
}
