status_mapping = {
    "LT": {"LT-100": {"status": "lost", "sub_status": "lost"}},
    "DL": {
        "EOD-38": {"status": "delivered", "sub_status": "delivered"},
        "RD-AC": {"status": "RTO", "sub_status": "RTO delivered"},
        "EOD-37": {"status": "delivered", "sub_status": "delivered"},
        "EOD-36": {"status": "delivered", "sub_status": "delivered"},
        "SC-101": {"status": "delivered", "sub_status": "delivered"},
    },
    "UD": {
        "EOD-43": {"status": "in transit", "sub_status": "in transit"},
        "U-PMA": {"status": "in transit", "sub_status": "in transit"},
        "EOD-15": {"status": "NDR", "sub_status": "NDR"},
        "DLYRG-125": {"status": "in transit", "sub_status": "in transit"},
        "X-UCI": {"status": "booked", "sub_status": "shipment booked"},
        "FMPUR-101": {"status": "pickup", "sub_status": "pickup scheduled"},
        "FMOFP-101": {"status": "pickup", "sub_status": "out for pickup"},
        "FMEOD-152": {
            "status": "pickup",
            "sub_status": "Shipment not ready for pickup",
        },
        "DTUP-231": {"status": "in transit", "sub_status": "in transit"},
        "DLYSHRTBAG-115": {"status": "in transit", "sub_status": "in transit"},
        "DLYLH-12": {"status": "in transit", "sub_status": "in transit"},
        "X-OLL4F": {"status": "in transit", "sub_status": "in transit"},
        "DLYMR-118": {"status": "in transit", "sub_status": "in transit"},
        "EOD-104": {"status": "NDR", "sub_status": "NDR"},
        "X-PPOM": {"status": "in transit", "sub_status": "picked up"},
        "X-DWS": {"status": "in transit", "sub_status": "in transit"},
        "X-PIOM": {"status": "in transit", "sub_status": "in transit"},
        "X-DBL1F": {"status": "in transit", "sub_status": "in transit"},
        "X-DLL2F": {"status": "in transit", "sub_status": "in transit"},
        "DLYLH-105": {"status": "in transit", "sub_status": "in transit"},
        "X-ILL2F": {"status": "in transit", "sub_status": "in transit"},
        "X-ILL1F": {"status": "in transit", "sub_status": "in transit"},
        "X-IBD3F": {"status": "in transit", "sub_status": "in transit"},
        "CS-CSL": {"status": "in transit", "sub_status": "in transit"},
        "X-DDD3FD": {"status": "out for delivery", "sub_status": "out for delivery"},
        "ST-114": {"status": "out for delivery", "sub_status": "out for delivery"},
        "ST-108": {"status": "NDR", "sub_status": "NDR"},
        "EOD-111": {"status": "NDR", "sub_status": "NDR"},
        "EOD-6O": {"status": "NDR", "sub_status": "NDR"},
        "EOD-6": {"status": "NDR", "sub_status": "NDR"},
        "X-AWD": {"status": "in transit", "sub_status": "in transit"},
        "EOD-11": {"status": "NDR", "sub_status": "NDR"},
        "EOD-74": {"status": "NDR", "sub_status": "NDR"},
        "DLYDC-101": {"status": "in transit", "sub_status": "in transit"},
        "DTUP-219": {"status": "pickup", "sub_status": "pickup pending"},
        "X-UNEX": {"status": "in transit", "sub_status": "in transit"},
        "X-PROM": {"status": "in transit", "sub_status": "in transit"},
        "X-OLL2F": {"status": "in transit", "sub_status": "in transit"},
        "DLYLH-133": {"status": "in transit", "sub_status": "in transit"},
        "EOD-3": {"status": "in transit", "sub_status": "in transit"},
        "FMEOD-108": {"status": "in transit", "sub_status": "in transit"},
        "DLYLH-106": {"status": "in transit", "sub_status": "in transit"},
        "DLYSHRTBAG-115": {"status": "in transit", "sub_status": "in transit"},
        "DLYLH-136": {"status": "in transit", "sub_status": "in transit"},
        "DLYRG-125": {"status": "in transit", "sub_status": "in transit"},
        "FMEOD-108": {"status": "in transit", "sub_status": "in transit"},
        "EOD-69": {"status": "NDR", "sub_status": "NDR"},
        "EOD-86": {"status": "NDR", "sub_status": "NDR"},
        "DLYLH-126": {"status": "in transit", "sub_status": "in transit"},
        "ST-102": {
            "status": "pickup",
            "sub_status": "bad / incomplete address",
        },
        "S-MAR": {
            "status": "in transit",
            "sub_status": "air restricted product, move by surface",
        },
        "S-TAT2": {
            "status": "in transit",
            "sub_status": "moved via surface",
        },
        "PL-105": {
            "status": "delivered",
            "sub_status": "delivered",
        },
        "CS-104": {"status": "in transit", "sub_status": "in transit"},
        "CS-101": {"status": "in transit", "sub_status": "in transit"},
        "DLYDC-107": {"status": "in transit", "sub_status": "in transit"},
        "X-SC": {"status": "in transit", "sub_status": "in transit"},
        "ST-120": {"status": "in transit", "sub_status": "in transit"},
        "DTUP-207": {"status": "in transit", "sub_status": "in transit"},
        "DTUP-205": {"status": "in transit", "sub_status": "in transit"},
        "X-PNP": {"status": "pickup", "sub_status": "pickup failed"},
        "FMEOD-103": {"status": "pickup", "sub_status": "pickup failed"},
    },
    "RT": {
        "L-PMA": {"status": "RTO", "sub_status": "untraceable"},
        "DLYRG-125": {"status": "RTO", "sub_status": "RTO in transit"},
        "U-PMA": {"status": "RTO", "sub_status": "RTO in transit"},
        "X-SC": {"status": "RTO", "sub_status": "RTO in transit"},
        "ST-120": {"status": "RTO", "sub_status": "RTO in transit"},
        "DLYSHRTBAG-115": {"status": "RTO", "sub_status": "RTO in transit"},
        "CS-101": {"status": "RTO", "sub_status": "RTO in transit"},
        "X-UCI": {"status": "RTO", "sub_status": "RTO initiated"},
        "FMPUR-101": {"status": "RTO", "sub_status": "RTO initiated"},
        "FMOFP-101": {"status": "RTO", "sub_status": "RTO initiated"},
        "CS-104": {"status": "RTO", "sub_status": "RTO in transit"},
        "FMEOD-152": {
            "status": "RTO",
            "sub_status": "RTO initiated",
        },
        "X-PPOM": {"status": "RTO", "sub_status": "RTO in transit"},
        "X-DWS": {"status": "RTO", "sub_status": "RTO in transit"},
        "X-PIOM": {"status": "RTO", "sub_status": "RTO in transit"},
        "X-DBL1F": {"status": "RTO", "sub_status": "RTO in transit"},
        "X-DLL2F": {"status": "RTO", "sub_status": "RTO in transit"},
        "DLYLH-105": {"status": "RTO", "sub_status": "RTO in transit"},
        "X-ILL2F": {"status": "RTO", "sub_status": "RTO in transit"},
        "X-ILL1F": {"status": "RTO", "sub_status": "RTO in transit"},
        "X-IBD3F": {"status": "RTO", "sub_status": "RTO in transit"},
        "CS-CSL": {"status": "RTO", "sub_status": "RTO in transit"},
        "X-DDD3FD": {"status": "RTO", "sub_status": "RTO out for delivery"},
        "ST-114": {"status": "RTO", "sub_status": "RTO out for delivery"},
        "EOD-111": {"status": "RTO", "sub_status": "NDR"},
        "RT-108": {"status": "RTO", "sub_status": "RTO initiated"},
        "DLYDC-101": {"status": "RTO", "sub_status": "RTO in transit"},
        "DTUP-219": {"status": "RTO", "sub_status": "RTO in transit"},
        "X-UNEX": {"status": "RTO", "sub_status": "RTO in transit"},
        "X-OLL2F": {"status": "RTO", "sub_status": "RTO in transit"},
    },
}
