status_mapping = {
    "new": {"status": "booked", "sub_status": "booked"},
    "picked": {"status": "in transit", "sub_status": "picked up"},
    "pickup_not_attempted": {"status": "pickup", "sub_status": "picked rescheduled"},
    "assigned_for_delivery": {
        "status": "out for delivery",
        "sub_status": "out for delivery",
    },
    "ofd": {
        "status": "out for delivery",
        "sub_status": "out for delivery",
    },
    "ofp": {"status": "pickup", "sub_status": "out for pickup"},
    "seller_not_contactable": {"status": "pickup", "sub_status": "picked failed"},
    "na": {"status": "NDR", "sub_status": "NDR"},
    "recd_at_rev_hub": {"status": "in transit", "sub_status": "in transit"},
    "delivered": {"status": "delivered", "sub_status": "delivered"},
    "assigned_for_seller_pickup": {"status": "pickup", "sub_status": "picked pending"},
    "pickup_on_hold": {"status": "pickup", "sub_status": "picked pending"},
    "item_manifested": {"status": "in transit", "sub_status": "in transit"},
    "recd_at_fwd_hub": {"status": "in transit", "sub_status": "in transit"},
    "recd_at_fwd_dc": {"status": "in transit", "sub_status": "in transit"},
    "cancelled_by_seller": {"status": "cancelled", "sub_status": "cancelled"},
    "rts_in_process": {"status": "RTO", "sub_status": "RTO in transit"},
    "received_at_rts_hub": {"status": "RTO", "sub_status": "RTO in transit"},
    "rts_ofd": {"status": "RTO", "sub_status": "RTO out for delivery"},
    "rts": {"status": "RTO", "sub_status": "RTO initiated"},
    "rts_nd": {"status": "RTO", "sub_status": "RTO in transit"},
    "recd_at_dc_rts": {"status": "RTO", "sub_status": "RTO in transit"},
    "cid": {"status": "NDR", "sub_status": "NDR"},
    "seller_initiated_delay": {"status": "pickup", "sub_status": "pickup rescheduled"},
    "in_transit_return": {"status": "RTO in transit", "sub_status": "RTO in transit"},
    "bag_received": {"status": "in transit", "sub_status": "in transit"},
    "bag_received_at_via": {"status": "in transit", "sub_status": "in transit"},
    "bag_in_transit": {"status": "in transit", "sub_status": "in transit"},
    "item_misrouted": {"status": "in transit", "sub_status": "in transit"},
    "pincode_updated": {"status": "in transit", "sub_status": "in transit"},
    "on_hold": {"status": "in transit", "sub_status": "in transit"},
    "lost": {"status": "lost", "sub_status": "lost"},
    "nc": {"status": "NDR", "sub_status": "NDR"},
    "reopen_ndr": {"status": "NDR", "sub_status": "NDR"},
    "cancelled_by_customer": {"status": "NDR", "sub_status": "NDR"},
    "rts_d": {"status": "RTO", "sub_status": "RTO delivered"},
}
